### ISSUE TITLE
Missing License information

### ISSUE THREAD

**Issue by jhermann** [jcuda/jcuda-main#12]
Please add a LICENSE file to this and the related projects – otherwise nobody can use this code without taking legal risks.

http://choosealicense.com/

**Comment by jcuda** [comment]
In doubt, the license is stated at http://www.jcuda.org/License.txt (and in each and every source code file). But you're right: I'll add LICENSE files here in GitHub as well.

**Comment by jcuda** [comment]
The MIT license files have been added to all JCuda repositories.
