### ISSUE TITLE
compatibility with cuda v9

### ISSUE THREAD

**Issue by balyszyn** [jcuda/jcuda-main#19]
**Is it planned to add compatibility with cuda 9 in the near future?**

**Comment by jcuda** [comment]
The update for CUDA 9.0 has already been asked for in https://github.com/jcuda/jcuda/issues/12#issuecomment-335010118 

I'll need a few more days, but hope that I can do the main update not later than next week. 

There are some internal refactorings going on, and it's not yet entirely clear which of them will already be part of the next release. 

Closing here for now, further details can be discussed in the linked issue.
