### ISSUE TITLE
Native libraries not found on Linux

### ISSUE THREAD

**Issue by btbouwens** [jcuda/jcuda-main#2]
After fixing the `CMakeLists.txt` to match the directory names, I could build the native libraries; they went into the `jcuda-main/build/lib/` directory, e.g. `jcuda-main/build/lib/libJCudaRuntime-linux-x86_64.so`, i.e. a subdirectory of the build directory specified.

Subsequently I try to build the Java code, but that fails with
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install (default-install) on project JCudaRuntime-native: Failed to install artifact org.jcuda:JCudaRuntime-native:so:linux-x86_64:0.7.5: /home/bram/project/JCuda/jcuda/JCudaRuntimeJNI/nativeLibrary/JCudaRuntime-linux-x86_64.so (No such file or directory) -> [Help 1]
```
which means the library is expected in a different directory (the `CMakeLists.txt` could specify where to put them) but the name is also wrong: library names start with `lib` usually.

**Comment by jcuda** [comment]
The target directory for the native libraries is set in the common CMake file: 
https://github.com/jcuda/jcuda-common/blob/955710131de19a21739401098f5618f9f0a5a261/JCudaCommon_CMake.txt#L45

So each native library should end in a `nativeLibrary` subdirectory of the respective project source directory. E.g. for JCufft it should end in
`JCufftJNI\nativeLibrary\`
(There it is expected by the corresponding POM for the native library)

However, I think according to 
https://cmake.org/cmake/help/v2.8.8/cmake.html#prop_tgt:RUNTIME_OUTPUT_DIRECTORY 
it is also necessary to set the `CMAKE_LIBRARY_OUTPUT_DIRECTORY` for Linux (or "non-DLL-platforms, as they call it).

I have changed the CMake file accordingly. 

I also added another property in the POMs to fix the library name. The `${jcuda.prefix}` is set to be `"lib"` on Linux/Mac (and the empty string on Windows), and this prefix is attached before the filename. 

Does this solve the issues? 

(Apologies, the transitiaion from a (Windows-Only) local SVN with custom build files to a GIT repo and a Maven build has some caveats...)

**Comment by btbouwens** [comment]
Indeed this problem is fixed, but I run into a problem at a later stage, running jcuda.test.JCudaBasicBindingTest. I need to check if it's not a problem with my setup though.
[hs_err_pid9299.log.txt](https://github.com/jcuda/jcuda-main/files/51428/hs_err_pid9299.log.txt)

**Comment by jcuda** [comment]
It's not necessarily a problem with your setup. I'll open another issue for that.
