### ISSUE TITLE
Release of version 0.9.0

### ISSUE THREAD

**Issue by jcuda** [jcuda/jcuda-main#21]
In order to release version 0.9.0 to Maven Central, need the binaries for Linux and MacOS.

In https://github.com/jcuda/jcuda-main/issues/14#issuecomment-278736545 , @blueberry, @MysterionRise @nakul02 offered binaries or their support. 

Does anybody have the chance to provide these binaries? 

I just created a tag for this "release candidate" that may serve as a basis for building the binaries. So after cloning/updating the repositories, the tag may be checked out with

    git checkout tags/version-0.9.0-RC00

in order to build the binaries based on that.

**Comment by blueberry** [comment]
I'll provide binaries for Linux, if the build process is similar to JOCL. If not, please point me to the right docs.

**Comment by blueberry** [comment]
is this up-to-date? https://github.com/jcuda/jcuda-main/blob/master/BUILDING.md

**Comment by jcuda** [comment]
@blueberry Yes, the process is similar to that of JOCL. The BUILDING.md is up to date - at least, the general description: The "build script" at the bottom was contributed by someone else, and I'm not entirely sure whether it might be necessary to update it. (If you find out that it does no longer work, I'll remove it).

**Comment by blueberry** [comment]
@jcuda The current build fails on my machine: https://github.com/jcuda/jcuda/issues/14

**Comment by blueberry** [comment]
@jcuda Here is the Linux build:
[output.zip](https://github.com/jcuda/jcuda-main/files/1563284/output.zip)
**Password is 123456** I added it so that github doesn't complain about the *.so in the content of the archive.

@amherag Could you try to make the macOS build, if you have Nvidia hardware?

**Comment by blueberry** [comment]
@jcuda In the meanwhile, I've run my extensive test suite for neanderthal and clojurecuda, and all tests pass with my build of JCuda 0.9.0 and CUDA 9.1.

**Comment by jcuda** [comment]
Thanks @blueberry , that's awesome. Also the tests. I know that the test coverage of JCuda is distressingly low, so I really appreciate that!

**Comment by blueberry** [comment]
@jcuda Marco, have you considered releasing 0.9.0 without macOS natives, and then releasing 0.9.1 with macOS natives when that's available?

PROS:
1. Majority of users want to or have to upgrade to CUDA 9 ald CUDNN 7.
2. Mac hardware with Nvidia CUDA is rather ancient. The last MacBook Pro with Nvidia is almost 5 years old. => It's difficult to build macOS binaries, and not many people need them.
3. Whoever really needs macOS binaries have 2 pretty good options with this scheme:
    a) contribute macOS binaries for 0.9.1!
    b) use JCuda 0.8.0
4. Faster release schedule for future updates, since we are always ready to build for Windows & Linux on short notice.

CONS:
1. Not so complete build (but, again, not many users have Nvidia hardware on macOS anyway).

**Comment by nakul02** [comment]
I second @blueberry s proposal. Getting access to a Mac with an Nvidia card is difficult to do right now. And going forward, maybe you could monitor any requests for jcuda support for Mac, and remove it eventually.

**Comment by jcuda** [comment]
In one sense, the problem might be smaller than it appears - from a technical point of view: The release of JCuda into Maven Central is done manually, by uploading the "Bundle" for each library. So I think that it should even be possible to just upload the JARs+Binaries that are available right now, and add the missing ones later. So I could create the 0.9.0 release without the Mac binaries, and as soon as they are available, they can be added, still having version 0.9.0. 

The devil may be in the detail, and there are some possible caveats. Of course, one has to make absolutely sure that the Mac binaries will eventually be built based on the source code that was tagged as version 0.9.0. But more generally: I *think* that this should work, but am not entirely sure (you know, Maven can be a b!tch and sometimes behaves "unexpectedly")

I wasn't aware of the fact that Mac does no longer use NVIDIA cards - does this only apply to the MacBooks, or also to the desktop systems? I'd assume that CUDA users would rather work with a desktop.

However, your arguments sound convincing, and I think doing a release with Win+Linux binaries should be worth a try. If the Mac binaries pop up, I can try to add them as 0.9.0, or, in doubt, release everything again as 0.9.0**b**. 

I'll try to do the release ASAP (probably beginning of next week).

**Comment by blueberry** [comment]
Hi Marco,

Here is the list of GPU hardware across Mac mahines: https://support.apple.com/en-us/HT202823
You can see that the lates desktops with Nvidia GPU (2009!, 2012) are even more ancient than laptop GPU (2013). They mostly come with Intel, and, alternatively, AMD Radeon hardware.

As for technical details of the maven repository, I would propose an even simpler solution:
1) Release 0.9.0 with Windows & Linux binaries
2) Prepare 0.9.1 (the same code as 0.9.0, but bumped up version data in pom.xml) that sits and waits for the macOS build

When that macOS build arrives, you simply upload to maven central the new version, which now supports all three operating systems. No need to mess up with the uploads or do anything non-standard.
Even if no one provides the mac builds by the time of 0.10.0, we can simply keep releasing Win&Lin builds for the new stuff until someone provides macOS binaries for the then-next release.
This option will also eliminate the problem that someone builds against an obsolete version, since the version in the queue is always the upcoming version (with the proper version in pom.xml, and proper tag in git, etc).

**Comment by hadim** [comment]
Will JCuda 0.9.0 be compatible with CUDA 9.1? I guess not since it's gonna look for libs such as libcufft.so.9.0 instead of libcufft.so.9.0.

Am I correct?

**Comment by blueberry** [comment]
I am using JCuda 0.9.0 that I built from the Marco's tagged source with CUDA 9.1 at the moment.

**Comment by jcuda** [comment]
@hadim  @blueberry  The point here may be: Did you build the JCuda binaries by linking against the CUDA 9.1 binaries? It may be possible to build the JCuda 0.9.0 and link it against the CUDA 9.1 libraries. But the resulting binaries might then only work for CUDA 9.1, and not for CUDA 9.0. Because it might indeed expect a libcufft.so.9.**1** somewhere. On the other hand, I think that the Linux "library version dependency resolution mechanism" involves some magic. So a JCuda binary that is built with CUDA 9.0 *might* also work with CUDA 9.1, but I doubt that.

(However, if the process for releasing JCuda 0.9.0 without the MacOs binaries works properly, the update to 9.1 could follow very soon - there likely are not many API changes, if there are any at all)

**Comment by blueberry** [comment]
@jcuda I built against 9.1 binaries. My shared library contains libcuda.so (and many other a bit more specific) symlinks that (I think) you refer as the linux magic. I haven't tried them with CUDA 8 - I assumed they should work with any (api compatible) older version of CUDA. Was I wrong?

**Comment by hadim** [comment]
Maybe you could look for `libcufft.so` instead of `libcufft.so.9.1` ?

That being said I don't know if you control the mechanism that detects the libraries on Linux system...

If it works you could just display a nice error message to the user to indicate there is a mismatch in between Cuda version?

**Comment by jcuda** [comment]
@blueberry 

> I haven't tried them with CUDA 8 - I assumed they should work with any (api compatible) older version of CUDA. Was I wrong?

Admittedly, I haven't checked whether CUDA 9 and 9.1 are API-compatible. If they are, the libraries *should* work, as long as there are no 9.1-specific paths or references. It's probably fiddly and inconvenient to test this (or to downgrade to CUDA 9.0 and compile the libs with that one), right?

<sub>(Assuming the "8" was a typo)</sub>

@hadim Unfortunately, a "nice" error message is difficult. The only thing that comes up is the "UnsatisfiedLinkError" when a library could not be loaded. This can happen for an awful number of reasons, and it's hard to figure out the reason (particularly, it does not say which dependency could not be found). 

(An aside: One of the things that I would do differently if I had the chance to re-write JCuda from scratch would probably be to add a dedicated `init()` method to catch this error before any JCuda function is called...)

**Comment by blueberry** [comment]
@jcuda 8 was *not* a typo. I assumed it should work with CUDA 8, as CUDA 9 should be mostly backwards compatible. (?)

Sorry, I can't downgrade right now, since my setup is a rather complex (and unusual) combination of nvidia and amd hardware with lots of screens on top, and most GPU-related things are installed from package manager, except nvidia gpu drivers that have to match pacman's version very closely. I'd had to fiddle with it to downgrade, and then I am not sure how easy it will be to upgrade again :)

**Comment by blueberry** [comment]
On the other hand, why not release what we have, and see how it works when people try it on different setups?

If we create a streamlined release process for minor updates, and we definitely can do this now that both Windows and Linux binaries are quickly available, we can rely on the actual users reporting real problems with different setups, rather than imagining problems that could happen (but most often don't :)
and solving those problems as we go.

**Comment by jcuda** [comment]
> CUDA 9 should be mostly backwards compatible. (?)

The question mark is the point ;-) I quickly skimmed over the 9.1 release notes, and did not see an API change - so I think that it *should* be backward compatible. But to be sure, I'd have to install it and check the headers (and even then, the truth can probably only be found by "trying it out"...)

In the best case, downgrading should not be necessary (I know that this can be fiddly)

Improving the deployment process would of course be desirable. The fact that the natives have to be available makes it difficult to use the `mvn release` infrastructure (because it puts *tags* into the Git repo, and there are several independent repos). But one simplification here (in contrast to JOCL, for example) is that the natives are contained in different, independent (!) artifacts. So technically, it's possible to add new natives (for the same version) later.

Let's give the 0.9.0 Win/Linux release path a try. Although I **strongly** want to avoid putting non-working binaries into Maven Central, taking this risk is probably the only way to find it out for sure.

**Comment by jcuda** [comment]
Version 0.9.0 should soon be available in Maven Central, at

    <dependency>
        <groupId>org.jcuda</groupId>
        <artifactId>jcuda</artifactId>
        <version>0.9.0</version>
    </dependency>
    <dependency>
        <groupId>org.jcuda</groupId>
        <artifactId>jcublas</artifactId>
        <version>0.9.0</version>
    </dependency>
    <dependency>
        <groupId>org.jcuda</groupId>
        <artifactId>jcufft</artifactId>
        <version>0.9.0</version>
    </dependency>
    <dependency>
        <groupId>org.jcuda</groupId>
        <artifactId>jcusparse</artifactId>
        <version>0.9.0</version>
    </dependency>
    <dependency>
        <groupId>org.jcuda</groupId>
        <artifactId>jcusolver</artifactId>
        <version>0.9.0</version>
    </dependency>
    <dependency>
        <groupId>org.jcuda</groupId>
        <artifactId>jcurand</artifactId>
        <version>0.9.0</version>
    </dependency>
    <dependency>
        <groupId>org.jcuda</groupId>
        <artifactId>jnvgraph</artifactId>
        <version>0.9.0</version>
    </dependency>

**Note** JCudnn is still missing. Since CUDNN is not part of "core" CUDA, it is built in a separate step. The process is basically the same as for the other libraries (creating the natives based on the JCudnnJNI/CMakeLists.txt and packaging it with Maven, except for that one still has to manually set the CUDNN installation path in CMake. I'll have to check whether I can make use of one of the `FindCUDNN.cmake` files that alreary seem to exist out there...)

@blueberry Do you think you could also provide the CUDNN7 + CUDA 9.(1/0) library for linux?

**Comment by blueberry** [comment]
Thank you, Marco!

Yes, I can provide binaries for CUDNN 7, just let me know when you decide it is ready for the build. Where do I set that path in CMake? In the config files, or as an argument?

**Comment by jcuda** [comment]
Yes, I should probably create a "jcudnn-0.9.0-RC" tag. I'll do this later today and drop you a note here.

Regarding the path: Usually, I use `cmake-gui`, where you simply insert the paths that create the "NOTFOUND" messages. If necessary, I can also add more details (possibly also how to set them programmatically)

**Comment by blueberry** [comment]
@jcuda I removed the existing jcuda folder from my local `.m2` folder.
When trying to build clojurecuda, I get:

```
Could not find artifact org.jcuda:jcuda-parent:pom:0.9.0 in central (https://repo1.maven.org/maven2/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

Indeed, jcuda-parent 0.9.0 is missing from the maven central: http://central.maven.org/maven2/org/jcuda/jcuda-parent/

It worked without changes with JCuda 0.9.0 that I built manually, and if I revert the version to 0.8.0, it downloads the artifacts from maven central. Any ideas?

**Comment by hadim** [comment]
I think I have a related issue when using:

```
		<dependency>
			<groupId>org.jcuda</groupId>
			<artifactId>jcufft</artifactId>
			<version>0.9.0</version>
		</dependency>
```

I got the following error:

```
Failed to collect dependencies at org.jcuda:jcufft:jar:0.9.0: Failed to read artifact descriptor for org.jcuda:jcufft:jar:0.9.0: Failure to find org.jcuda:jcuda-parent:pom:0.9.0 in http://maven.imagej.net/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of imagej.public has elapsed or updates are forced -> [Help 1]
```

Note that `http://maven.imagej.net/content/groups/public` is a mirror of Maven Central.

**Comment by jcuda** [comment]
Indeed, the `jcuda-parent` bundle was still missing. I have just added it. It may take a few minutes/hours(?) until it is promoted from Sonatype to Maven Central. Let's hope that this resolves this issue.

**Comment by blueberry** [comment]
Works like a charm now. Thank you.

**Comment by jcuda** [comment]
Great to hear that! 

(I already was afraid of having uploaded an "irrevocably broken" version...)

I also just tried it on Windows, and it seems to work.

@blueberry : I have created a tag for JCudnn from the current state, at https://github.com/jcuda/jcudnn/tree/version-0.9.0-RC00

**Comment by hadim** [comment]
I confirm it works on Ubuntu with Cuda 9.1 (will test on Windows soon).

**Comment by hadim** [comment]
It also works on Windows 10 with Cuda 9.0 for me.

**Comment by jcuda** [comment]
Great 👍  (I'll leave it open until the JCudnn release is out, and then I'll update to 9.1 ...)

**Comment by blueberry** [comment]
@jcuda Here is Jcudnn for linux: 
[jcudnn-natives-0.9.0-linux-x86_64.zip](https://github.com/jcuda/jcuda-main/files/1640579/jcudnn-natives-0.9.0-linux-x86_64.zip)

**Comment by jcuda** [comment]
Thanks @blueberry  for the JCudnn linux binaries!

The bundle has just been uploaded, and JCudnn 0.9.0 (for CUDNN 7) should soon be available in Maven Central, at

    <dependency>
        <groupId>org.jcuda</groupId>
        <artifactId>jcudnn</artifactId>
        <version>0.9.0</version>
    </dependency>

(I'll test the Windows version ASAP, and if everything works, this issue will be closed)

**Comment by jcuda** [comment]
There had been a problem with the Linux version. This was reported and is discussed in https://github.com/jcuda/jcuda-main/issues/24 , so I'll close this issue here.
