### ISSUE TITLE
Jcuda on OS X with CUDA 7.5

### ISSUE THREAD

**Issue by phvu** [jcuda/jcuda-main#4]
Just a reminder, in order to build `jcuda` on OS X El Capitan with CUDA 7.5, it is crucial to set 

```
CMAKE_EXE_LINKER_FLAGS='-Xlinker -F/Library/Frameworks -Xlinker -framework -Xlinker CUDA'
CMAKE_SHARED_LINKER_FLAGS='-Xlinker -F/Library/Frameworks -Xlinker -framework -Xlinker CUDA'
```

Those variables can be set in `cmake-ui` after select the `Advanced` option.

Ref: https://github.com/dmlc/mxnet/issues/728#issuecomment-160867057

Maybe adding this note into `README`?

**Comment by gpu** [comment]
Thanks for this hint. I'll have a closer look at what these flags do. (However, only the "SHARED" one should be relevant for JCuda, I guess).

Maybe it would be better to directly integrate this into the common CMake files, so that they are set automatically on MacOS? (I'm not sure whether this is specific for the given MacOS version, or can be set on all MacOS platforms...(?))

**Comment by jcuda** [comment]
Thanks for this hint. I'll have a closer look at what these flags do. (However, only the "SHARED" one should be relevant for JCuda, I guess).

Maybe this can be added to the common CMake file, so that it is automatically used on all MacOS platforms? (Or is it specific for the "El Capitain" version?)

**Comment by phvu** [comment]
Several months ago I used to compile `jcuda` on the previous version of OS X (10.10) and it worked smoothly. So I guess this is quite specific for OS X 10.11 (i.e. El Capitan).

**Comment by jcuda** [comment]
OK, I searched for this, and think that adding something like the following to the common CMake file could solve the issue:

```
if(CMAKE_HOST_APPLE)
    # The compilation on MacOS >=10.11 and above requires additional
    # linker flags. In order to detect whether MacOS >=10.11 is present,
    # the underlying Darwin version number is checked here (see
    # https://en.wikipedia.org/wiki/Darwin_%28operating_system%29)
    # If it is greater than 14, then MacOS 10.11 or greater is running
    string(REGEX REPLACE "^([0-9]+)\\.([0-9]+).*$" "\\1" 
        DARWIN_MAJOR_VERSION ${CMAKE_SYSTEM_VERSION})
    message("Darwin major version is ${DARWIN_MAJOR_VERSION}")
    if(${DARWIN_MAJOR_VERSION} GREATER 14)
        message("Found El Capitan")
        set(CMAKE_SHARED_LINKER_FLAGS ${CMAKE_SHARED_LINKER_FLAGS}
            "-Xlinker -F/Library/Frameworks -Xlinker -framework -Xlinker CUDA") 
    else()
        message("Did NOT find El Capitan")
    endif()
endif()
```

Since I can not test it: Can you confirm that adding this at the beginning of https://github.com/jcuda/jcuda-common/blob/master/JCudaCommon_CMake.txt solves the issue? (If not, it should at least print some version information)

**Comment by phvu** [comment]
Hmm I saw the log message `Found El Capitan`, but the variable is still not set.
I even tried to put only the `set()` command (without the other logic), but still it doesn't work. The variable is still empty in CMake UI.

**Comment by jcuda** [comment]
Sorry, I think I got the quotes wrong: It should be

    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Xlinker -F/Library/Frameworks -Xlinker -framework -Xlinker CUDA") 

(Otherwise, it will assign the empty value to itself...).

**Comment by phvu** [comment]
Yes I tried that too, but it doesn't work.

This is what I have in `JCudaCommon_CMake.txt`:

![](https://lh3.googleusercontent.com/zFGFwYGYls-jiNJ6InFBOG_8wXTgryXEMbV43XmQryslM4GQPBz71ZbKUHqgVu3Szbm6=w5760-h3600-rw-no "Setting")

And this is when I run "Generate" in CMake:

![](https://lh3.googleusercontent.com/-0pDQqVWjl3o/VvxyOIE1XtI/AAAAAAAACVw/bMh5ltofOecy3zv5gevW4Rqs16Rx6cL-ACCo/s640-Ic42/Screen%2BShot%2B2016-03-31%2Bat%2B7.31.54%2BAM.png "CMake")

Does it work on your system?

**Comment by jcuda** [comment]
The main goal of this test/snippet was to see whether it properly detects the right OS version (and a *basic* test to see whether it might work then).  

The variable setting will not appear in the CMake GUI. But it should still be passed to the actual linker call. (At least, I added it, and it did *not* appear in the CMake GUI, but in the Visual Studio command lines). 

(The `CMAKE_SHARED_LINKER_FLAGS` is something that is handled internally by CMake, and filled with some values as soon as it knows the target platform. E.g. on Win64, it will automagically be filled with `/machine:x64` - some MSVC specific setting. **When** exactly it is filled (and thus *when* it may be extended with the required parameters) seems to be unspecified - at least, I couldn't figure it out yet). 

So I'm not sure about the best way to integrate this. But I'll probably just put it into `JCudaCommon_CMake_flags.txt`, together with some 

    if (NOT CMAKE_CUDA_SHARED_LINKER_FLAGS_INITIALIZED)
        ...
        set(CMAKE_CUDA_SHARED_LINKER_FLAGS_INITIALIZED "true")
    endif()

guard. I'm pretty sure that this is not the best way to do it, but honestly: There are always so many options for achieving the (seemingly) same thing in CMake, and the scope of settings, override rules and caching policies is ... confusing, to say the least - so the only way to find out what a "good" solution is seems to be trial and error...

(I'm open for recommendations and hints, of course...)

**Comment by phvu** [comment]
Actually it works. You are right, the value is not shown in CMake UI, but it is still passed to the Makefiles, and I can compile it with `make all`.
Superb, feel free to fix it in any way you prefer. I am not an expert on CMake neither.

**Comment by jcuda** [comment]
So I added the linker flags in https://github.com/jcuda/jcuda-common/commit/740c7d84f85c394a7f330cfad72348f30eaebfd3 

I slightly changed the version detection - it would be great if you could test whether this still works as expected. Then this issue could be closed.

(Unfortunately, I noticed that there is another issue when compiling on Windows with VS 2015. It complains about an "unresolved external symbol _snprintf" in some of the CUBLAS functions. But this seems to be a CUBLAS issue, and I did not yet find a way to fix this)

**Comment by phvu** [comment]
I hate to say this, but the fix doesn't work. I pulled the latest code of `jcuda-common`, and this is the result when I run `make all`:

```
Linking CXX shared library /Users/vupham/lib/JCuda/jcuda/JCudaDriverJNI/nativeLibrary/libJCudaDriver-apple-x86_64.dylib
ld: file not found: @rpath/CUDA.framework/Versions/A/CUDA for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/Users/vupham/lib/JCuda/jcuda/JCudaDriverJNI/nativeLibrary/libJCudaDriver-apple-x86_64.dylib] Error 1
make[1]: *** [jcuda/JCudaDriverJNI/bin/CMakeFiles/JCudaDriver.dir/all] Error 2
make: *** [all] Error 2
```

Seems like the variable is not set.

However if I remove the code that you inserted in `JCudaCommon_CMake_flags.txt`, and put this into `JCudaCommon_CMake.txt`:

```
# The compilation on MacOS >=10.11 and above requires additional
# linker flags. In order to detect whether MacOS >=10.11 is present,
# the underlying Darwin version number is checked here (see
# https://en.wikipedia.org/wiki/Darwin_%28operating_system%29)
# If it is not less than 15.0.0, then MacOS 10.11 or greater is running.
# The flags are added ONCE, to the CMAKE_SHARED_LINKER_FLAGS variable
if(CMAKE_HOST_APPLE)
    string(REGEX REPLACE "^([0-9]+)\\.([0-9]+).*$" "\\1" DARWIN_MAJOR_VERSION ${CMAKE_SYSTEM_VERSION})
    if(${DARWIN_MAJOR_VERSION} GREATER 14)
        set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Xlinker -F/Library/Frameworks -Xlinker -framework -Xlinker CUDA") 
    endif()
endif()
```

(i.e. the old piece of code) then it works.

When I tried to put this into `JCudaCommon_CMake_flags.txt`:
```
# The compilation on MacOS >=10.11 and above requires additional
# linker flags. In order to detect whether MacOS >=10.11 is present,
# the underlying Darwin version number is checked here (see
# https://en.wikipedia.org/wiki/Darwin_%28operating_system%29)
# If it is not less than 15.0.0, then MacOS 10.11 or greater is running.
# The flags are added ONCE, to the CMAKE_SHARED_LINKER_FLAGS variable
if (NOT CMAKE_CUDA_SHARED_LINKER_FLAGS_INITIALIZED)
    if(CMAKE_HOST_APPLE)
        string(REGEX REPLACE "^([0-9]+)\\.([0-9]+).*$" "\\1" DARWIN_MAJOR_VERSION ${CMAKE_SYSTEM_VERSION})
        if(${DARWIN_MAJOR_VERSION} GREATER 14)
            set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Xlinker -F/Library/Frameworks -Xlinker -framework -Xlinker CUDA") 
        endif()
    endif()
    set(CMAKE_CUDA_SHARED_LINKER_FLAGS_INITIALIZED "true")
endif()
```
then it says 
```
CMake Error at <...>/JCuda/jcuda-common/JCudaCommon_CMake_flags.txt:22 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:3 (include)


CMake Error at <...>/JCuda/jcuda-common/JCudaCommon_CMake_flags.txt:23 (if):
  if given arguments:

    "GREATER" "14"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:3 (include)


Configuring incomplete, errors occurred!
```

I am using cmake 3.5.1, if that matters.

**Comment by jcuda** [comment]
OK, this is a bit odd. Basically, the main difference of 
`JCudaCommon_CMake_flags.txt` and
'JCudaCommon_CMake.txt`
is that the first one is included *before* the `project` definitions, and the second one is included *after* the `project` definitions. As I said, the criteria and conditions of *which* setting should be done *where* is rather intransparent (and seems to boil down to "In one case it works, in the other it doesn't"). However, I now moved the setting to the common CMake file again: https://github.com/jcuda/jcuda-common/commit/457101b89011bf75126fdcb935ca4bc527f42372 

Let's hope this is the case where it works. (I'll probably have to read more about CMake and this variable and settings caching stuff, and its debugging facilities. I don't like using `message`s to reverse engineer what it is doing internally...)

**Comment by phvu** [comment]
Yes I can confirm it works now!
