### ISSUE TITLE
Compatibility release for CUDA 11.6

### ISSUE THREAD

**Issue by jcuda** [jcuda/jcuda-main#52]
There have been issues related to compatibility problems of JCuda on Linux, related to the GLIBC version that was used for building the Linux binaries ( https://github.com/jcuda/jcuda-main/issues/45 and https://github.com/jcuda/jcuda-main/issues/51 )

I have created a compatibility release of JCuda for CUDA 11.6. In this release, the Linux binaries are those provided by @corepointer , as mentioned in [this comment](https://github.com/jcuda/jcuda-main/issues/51#issuecomment-1164390291), which should only require an older GLIBC version.

The version number is 11.6.1**b**, and it is available under
```
<dependency>
    <groupId>org.jcuda</groupId>
    <artifactId>jcuda</artifactId>
    <version>11.6.1b</version>
</dependency>
<dependency>
    <groupId>org.jcuda</groupId>
    <artifactId>jcublas</artifactId>
    <version>11.6.1b</version>
</dependency>
<dependency>
    <groupId>org.jcuda</groupId>
    <artifactId>jcufft</artifactId>
    <version>11.6.1b</version>
</dependency>
<dependency>
    <groupId>org.jcuda</groupId>
    <artifactId>jcusparse</artifactId>
    <version>11.6.1b</version>
</dependency>
<dependency>
    <groupId>org.jcuda</groupId>
    <artifactId>jcusolver</artifactId>
    <version>11.6.1b</version>
</dependency>
<dependency>
    <groupId>org.jcuda</groupId>
    <artifactId>jcurand</artifactId>
    <version>11.6.1b</version>
</dependency>
<dependency>
    <groupId>org.jcuda</groupId>
    <artifactId>jcudnn</artifactId>
    <version>11.6.1b</version>
</dependency>
```

Note: This release involved quite a bunch of manual steps, for various reasons. I tried to be careful, but it's not unlikely that I forgot to insert this **'b'** in some filename or POM. The state of this release is in a branch `release-11.6.1b` in all relevant repositories. The master branch will be unaffected by this, because it is really only a new _release_ without actual code changes, except for the version numbers.

Maybe someone with a Linux system can try it out ( @blueberry @ACheekyLlama @corepointer ), and if there is any problem, please let me know.

**Comment by ACheekyLlama** [comment]
Can confirm this is working on Debian 11 - thank you very much for the quick fix!
